### ISSUE TITLE
Evaluate mapToTheme inside another function

### ISSUE THREAD

**Issue by davelab** [scf4/styled-map#4]
Hi thanks for this useful library!
I'm trying to pass mapToTheme returned value inside another function from a styled-component

what I aim to do is lighten a color:
`
  &:hover,
  &:focus {
    background-color: ${colorManipulation.lighten(mapToTheme('ButtonHoverBackground'), 0.5)}
  }
`

but `mapToTheme('ButtonHoverBackground')` it returns the function definition. the entire style is:

export default ({theme, ...props}) => css`
  box-sizing: border-box;
  appearance: none;
  border: none;
  cursor: pointer;
  display: inline-block;
  min-height: 1rem;
  outline: none;
  text-align: center;
  text-decoration: none;
  user-select: none;
  overflow: hidden;
  transition: background-color 0.25s linear;
  padding: 0 1.4rem;

  border-radius: ${theme.ButtonCommon.borderRadius};
  background-color: ${mapToTheme('ButtonBackground')};
  color: ${mapToTheme('ButtonColor')};
  border: ${props.outline && '1px solid'};
  width: ${props.fluid ? '100%' : 'auto'};

  ${mapToTheme('ButtonSize')}

  &:hover,
  &:focus {
   background-color: ${colorManipulation.lighten(mapToTheme('ButtonBackground'), 0.5)}
   }

  ${props.disabled && `
    pointer-events: none;
    cursor: not-allowed;
  `}
`

**Comment by scf4** [comment]
Hi @davelab 

I could add a second parameter to `mapToTheme` which takes a function to call on the result (and passes through the rest of the params), to let you do this:

```js
const Button = styled.button`
  background: mapToTheme('buttonColor', colorManipulation.lighten, 0.5);
`;
```

But I wonder if this is starting to complicate things.

What does this part of your theme object look like? Is there a reason you're lightening the color here instead of when you define it in the theme object?
